import colors from './colors';
import metrics from './metrics';
import text from './text';

export default {
  box: {
    backgroundColor: colors.white,
    borderRadius: metrics.baseRadius,
    padding: metrics.basePadding,
  },
  line: {
    borderBottomColor: colors.lightGrey,
    borderBottomWidth: 1,
  },
  lineOrange: {
    borderBottomColor: colors.orange,
    borderBottomWidth: 1,
  },
  lineLight: {
    borderBottomColor: colors.lightGreyOpacity40,
    borderBottomWidth: 1,
  },
  btnDefault: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.orange,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnDanger: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.red,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnSuccess: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.green,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnWarning: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.yellow,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnPurple: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnDark: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.dark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnDarkLight: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.littledark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnMessageSystem: {
    padding: metrics.baseMargin10,
    borderRadius: metrics.baseRadius,
    backgroundColor: colors.whiteTransparent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnBack: {
    paddingHorizontal: metrics.baseMargin10,
    width: metrics.baseMargin20 * 2,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boxCircle100: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.light,
  },
  boxCircle75: {
    width: 75,
    height: 75,
    borderRadius: 37.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.light,
  },
  boxCircle50: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.light,
  },
  boxCircle35: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.light,
  },
  badge: {
    padding: 3,
    paddingHorizontal: 6,
    borderRadius: metrics.baseRadius,
    alignSelf: 'flex-start',
  },
  badgeRed: {
    padding: 3,
    paddingHorizontal: 6,
    backgroundColor: colors.red,
    color: colors.white,
    borderRadius: metrics.baseRadius,
    alignSelf: 'flex-start',
  },
  badgeBlack: {
    padding: 3,
    paddingHorizontal: 6,
    backgroundColor: colors.blackOpacity50,
    color: colors.white,
    borderRadius: metrics.baseRadius,
    alignSelf: 'flex-start',
  },
  badgeGray: {
    padding: 3,
    paddingHorizontal: 6,
    backgroundColor: colors.lighter,
    color: colors.dark,
    borderRadius: metrics.baseRadius,
    alignSelf: 'flex-start',
  },
  badgeWhite: {
    padding: 3,
    paddingHorizontal: 6,
    backgroundColor: colors.whiteTransparent,
    color: colors.white,
    borderRadius: metrics.baseRadius,
    alignSelf: 'flex-start',
  },
  inputDefault: {
    ...text.h6,
    borderColor: colors.light,
    borderWidth: 1,
    borderRadius: metrics.baseMargin5,
    backgroundColor: colors.white,
    padding: 10,
    marginVertical: metrics.baseMargin10,
    height: 42,
  },
  titleGeneral: {
    ...text.h5,
    color: colors.orange,
    marginTop: metrics.baseMargin10,
  },
};
